use db;

CREATE TABLE CUSTOMER(
    ID varchar(36) ,
    FIRST_NAME varchar(36),
    LAST_NAME varchar(36),
    EMAIL_ID varchar(40),
    ADDRESS varchar(50),
    PHONE_NUMBER VARCHAR(12) NOT NULL,
    VIP BOOLEAN,
    PRIMARY KEY(ID)
);


CREATE TABLE APPOINTMENT (
  ID INT AUTO_INCREMENT,
  FIRST_NAME VARCHAR(36),
  LAST_NAME VARCHAR(36),
  PHONE_NUMBER VARCHAR(12) NOT NULL,
  VIP BOOLEAN DEFAULT 0,
  STATUS ENUM('waiting', 'resolved', 'cancelled') DEFAULT 'waiting',
  CHECK_IN_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

