INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('1', 'John', 'Doe', 'johndoe@example.com', '123 Main St', '555-555-1212', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('2', 'Jane', 'Doe', 'janedoe@example.com', '456 Main St', '555-555-1213', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('3', 'Jim', 'Smith', 'jimsmith@example.com', '789 Main St', '555-555-1214', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('4', 'Sarah', 'Johnson', 'sarahjohnson@example.com', '111 Main St', '555-555-1215', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('5', 'Tom', 'Brown', 'tombrown@example.com', '222 Main St', '555-555-1216', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('6', 'Alice', 'Davis', 'alicedavis@example.com', '333 Main St', '555-555-1217', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('7', 'Bob', 'Miller', 'bobmiller@example.com', '444 Main St', '555-555-1218', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('8', 'Emma', 'Wilson', 'emmawilson@example.com', '555 Main St', '555-555-1219', 0);

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL_ID, ADDRESS, PHONE_NUMBER, VIP)
VALUES ('9', 'Michael', 'Taylor', 'michaeltaylor@example.com', '666 Main St', '555-555-1220', 0);

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('John', 'Doe', '555-555-1212', 1, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Jane', 'Doe', '555-555-1213', 0, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Jim', 'Smith', '555-555-1214', 1, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Sarah', 'Johnson', '555-555-1215', 1, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Tom', 'Brown', '555-555-1216', 0, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Alice', 'Davis', '555-555-1217', 1, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Bob', 'Miller', '555-555-1218', 0, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Emma', 'Wilson', '555-555-1219', 1, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Michael', 'Taylor', '555-555-1220', 0, NOW());

-- INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER, VIP, CHECK_IN_TIME)
-- VALUES ('Emily', 'Parker', '555-555-1221', 1, NOW());
